from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image

from yd_vector.models import TraceOptions, TraceResult
from yd_vector.preprocess import preprocess_image
from yd_vector.utils import ensure_parent_dir

# PurePythonTracer lives in the project root (one level above this package).
# Attempt a direct import; if that fails (e.g. running from inside the package),
# insert the project root into sys.path first.
try:
    from tracer import PurePythonTracer
except ImportError:
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from tracer import PurePythonTracer


def run_trace(options: TraceOptions) -> TraceResult:
    """Run the full Potrace-style pipeline via PurePythonTracer.

    Replaces the legacy cv2.findContours + Douglas-Peucker + straight-line
    pipeline.  All SVG output is now generated by tracer.py which uses the
    faithful Potrace bitmap-walk + Bezier-fitting + optiCurve stages.

    Args:
        options: TraceOptions dataclass (input/output paths, threshold, etc.)

    Returns:
        TraceResult with svg_path set; contours/fitted_paths are empty (they
        are internal to the Potrace pipeline and not exposed here).
    """
    rgb, gray, binary = preprocess_image(
        image_path=str(options.input_path),
        threshold=options.threshold,
        invert=options.invert,
    )
    height, width = gray.shape[:2]

    tracer = PurePythonTracer()
    svg_str = tracer.trace(binary, fill=options.fill)

    svg_path = ensure_parent_dir(options.output_path)
    svg_path.write_text(svg_str, encoding="utf-8")

    debug_mask_path = None
    if options.debug:
        debug_mask_path = options.output_path.parent / f"{options.output_path.stem}_mask.png"
        ensure_parent_dir(debug_mask_path)
        Image.fromarray(binary).save(debug_mask_path)

    return TraceResult(
        width=width,
        height=height,
        contours=[],
        fitted_paths=[],
        svg_path=svg_path,
        debug_mask_path=debug_mask_path,
    )
