from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image

from yd_vector.models import TraceOptions, TraceResult
from yd_vector.preprocess import preprocess_image
from yd_vector.utils import ensure_parent_dir

import potrace


def run_trace(options: TraceOptions) -> TraceResult:
    """Run the full Potrace-style pipeline via PurePythonTracer.

    Replaces the legacy cv2.findContours + Douglas-Peucker + straight-line
    pipeline.  All SVG output is now generated by tracer.py which uses the
    faithful Potrace bitmap-walk + Bezier-fitting + optiCurve stages.

    Args:
        options: TraceOptions dataclass (input/output paths, threshold, etc.)

    Returns:
        TraceResult with svg_path set; contours/fitted_paths are empty (they
        are internal to the Potrace pipeline and not exposed here).
    """
    rgb, gray, binary = preprocess_image(
        image_path=str(options.input_path),
        threshold=options.threshold,
        invert=options.invert,
    )
    height, width = gray.shape[:2]

    bmp = potrace.Bitmap(binary.astype(bool))
    path = bmp.trace(
        turdsize=2,
        turnpolicy=potrace.TURNPOLICY_MINORITY,
        alphamax=1.0,
        opticurve=True,
        opttolerance=0.2,
    )

    svg_paths = []
    for curve in path:
        parts = [f"M {curve.start_point.x:.3f} {curve.start_point.y:.3f}"]
        for segment in curve:
            if segment.is_corner:
                parts.append(f"L {segment.c.x:.3f} {segment.c.y:.3f} L {segment.end_point.x:.3f} {segment.end_point.y:.3f}")
            else:
                parts.append(
                    f"C {segment.c1.x:.3f} {segment.c1.y:.3f} "
                    f"{segment.c2.x:.3f} {segment.c2.y:.3f} "
                    f"{segment.end_point.x:.3f} {segment.end_point.y:.3f}"
                )
        parts.append("Z")
        svg_paths.append(" ".join(parts))

    d_string = " ".join(svg_paths)
    svg_str = f'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">\n  <path d="{d_string}" fill="{options.fill}" fill-rule="evenodd" stroke="none"/>\n</svg>\n'

    svg_path = ensure_parent_dir(options.output_path)
    svg_path.write_text(svg_str, encoding="utf-8")

    debug_mask_path = None
    if options.debug:
        debug_mask_path = options.output_path.parent / f"{options.output_path.stem}_mask.png"
        ensure_parent_dir(debug_mask_path)
        Image.fromarray(binary).save(debug_mask_path)

    return TraceResult(
        width=width,
        height=height,
        contours=[],
        fitted_paths=[],
        svg_path=svg_path,
        debug_mask_path=debug_mask_path,
    )
